/* ============================================================
   plants.js — Plant library
   spacing / spread / height in meters. minHours = direct sun
   hours needed per day. sun: full ≥6h, part 4–6h, shade <4h ok.
   ============================================================ */

const SUN_LEVELS = {
  full:  { label: 'Full sun',  minHours: 6, icon: '☀️' },
  part:  { label: 'Part sun',  minHours: 4, icon: '⛅' },
  shade: { label: 'Shade ok',  minHours: 2, icon: '🌥' },
};

const PLANTS = [
  // ---------- Vegetables ----------
  { id: 'tomato', name: 'Tomato', botanical: 'Solanum lycopersicum', emoji: '🍅', cat: 'Vegetables',
    sun: 'full', spacing: 0.6, spread: 0.6, height: 1.5, water: 'high', days: '60–85 days',
    sow: 'Transplant 1–2 wks after last frost', companions: ['basil', 'marigold', 'carrot', 'garlic'],
    avoid: ['potato', 'corn', 'fennel', 'broccoli'],
    tip: 'Deep, infrequent watering prevents split fruit. Stake or cage at planting time.' },
  { id: 'pepper', name: 'Bell Pepper', botanical: 'Capsicum annuum', emoji: '🫑', cat: 'Vegetables',
    sun: 'full', spacing: 0.45, spread: 0.45, height: 0.8, water: 'medium', days: '60–90 days',
    sow: 'Transplant 2–3 wks after last frost', companions: ['basil', 'onion', 'carrot'],
    avoid: ['fennel', 'kale'],
    tip: 'Loves heat — the warmest, sunniest corner of the garden is pepper territory.' },
  { id: 'lettuce', name: 'Lettuce', botanical: 'Lactuca sativa', emoji: '🥬', cat: 'Vegetables',
    sun: 'part', spacing: 0.25, spread: 0.25, height: 0.25, water: 'medium', days: '45–60 days',
    sow: 'Direct sow 2–4 wks before last frost', companions: ['carrot', 'radish', 'strawberry', 'chive'],
    avoid: ['broccoli'],
    tip: 'Bolts in heat — afternoon shade from taller neighbors extends the harvest into summer.' },
  { id: 'carrot', name: 'Carrot', botanical: 'Daucus carota', emoji: '🥕', cat: 'Vegetables',
    sun: 'full', spacing: 0.08, spread: 0.08, height: 0.3, water: 'medium', days: '70–80 days',
    sow: 'Direct sow 3 wks before last frost', companions: ['tomato', 'onion', 'rosemary', 'chive'],
    avoid: ['dill'],
    tip: 'Needs loose, stone-free soil 30cm deep — raised beds are ideal.' },
  { id: 'cucumber', name: 'Cucumber', botanical: 'Cucumis sativus', emoji: '🥒', cat: 'Vegetables',
    sun: 'full', spacing: 0.45, spread: 0.9, height: 0.3, water: 'high', days: '50–70 days',
    sow: 'Direct sow after soil warms', companions: ['bean', 'radish', 'sunflower', 'dill'],
    avoid: ['potato', 'sage'],
    tip: 'Trellis vertically to save bed space and keep fruit straight and clean.' },
  { id: 'zucchini', name: 'Zucchini', botanical: 'Cucurbita pepo', emoji: '🥒', cat: 'Vegetables',
    sun: 'full', spacing: 0.9, spread: 1.2, height: 0.6, water: 'high', days: '45–55 days',
    sow: 'Direct sow after last frost', companions: ['nasturtium', 'bean', 'corn'],
    avoid: ['potato'],
    tip: 'One plant feeds a family. Two plants feed the neighborhood.' },
  { id: 'broccoli', name: 'Broccoli', botanical: 'Brassica oleracea', emoji: '🥦', cat: 'Vegetables',
    sun: 'full', spacing: 0.45, spread: 0.5, height: 0.6, water: 'medium', days: '60–80 days',
    sow: 'Transplant 2 wks before last frost', companions: ['onion', 'chamomile', 'beet'],
    avoid: ['tomato', 'strawberry'],
    tip: 'A cool-season crop — spring and fall plantings outperform summer ones.' },
  { id: 'kale', name: 'Kale', botanical: 'Brassica oleracea', emoji: '🥬', cat: 'Vegetables',
    sun: 'part', spacing: 0.4, spread: 0.5, height: 0.6, water: 'medium', days: '50–65 days',
    sow: 'Direct sow 4 wks before last frost', companions: ['beet', 'celery', 'onion'],
    avoid: ['pepper', 'strawberry'],
    tip: 'Frost sweetens the leaves — harvest right through early winter.' },
  { id: 'bean', name: 'Bush Bean', botanical: 'Phaseolus vulgaris', emoji: '🫘', cat: 'Vegetables',
    sun: 'full', spacing: 0.15, spread: 0.3, height: 0.5, water: 'medium', days: '50–60 days',
    sow: 'Direct sow after last frost', companions: ['cucumber', 'corn', 'strawberry', 'potato'],
    avoid: ['onion', 'garlic', 'chive'],
    tip: 'Fixes its own nitrogen — a natural fertilizer for heavy feeders nearby.' },
  { id: 'pea', name: 'Snap Pea', botanical: 'Pisum sativum', emoji: '🫛', cat: 'Vegetables',
    sun: 'part', spacing: 0.08, spread: 0.15, height: 1.5, water: 'medium', days: '55–70 days',
    sow: 'Direct sow as soon as soil works', companions: ['carrot', 'radish', 'cucumber'],
    avoid: ['onion', 'garlic'],
    tip: 'The first thing in the ground each spring. Needs a trellis from day one.' },
  { id: 'onion', name: 'Onion', botanical: 'Allium cepa', emoji: '🧅', cat: 'Vegetables',
    sun: 'full', spacing: 0.12, spread: 0.12, height: 0.45, water: 'low', days: '90–110 days',
    sow: 'Sets out 4 wks before last frost', companions: ['carrot', 'beet', 'lettuce', 'tomato'],
    avoid: ['bean', 'pea'],
    tip: 'Day-length sensitive — choose long-day varieties in the north, short-day in the south.' },
  { id: 'garlic', name: 'Garlic', botanical: 'Allium sativum', emoji: '🧄', cat: 'Vegetables',
    sun: 'full', spacing: 0.12, spread: 0.12, height: 0.5, water: 'low', days: '240 days (overwinter)',
    sow: 'Plant cloves in fall', companions: ['tomato', 'carrot', 'rose'],
    avoid: ['bean', 'pea'],
    tip: 'Plant in October, harvest in July. The easiest crop you will ever grow.' },
  { id: 'potato', name: 'Potato', botanical: 'Solanum tuberosum', emoji: '🥔', cat: 'Vegetables',
    sun: 'full', spacing: 0.3, spread: 0.45, height: 0.6, water: 'medium', days: '80–100 days',
    sow: 'Seed potatoes 2 wks before last frost', companions: ['bean', 'corn', 'marigold'],
    avoid: ['tomato', 'cucumber', 'zucchini'],
    tip: 'Hill soil around stems as they grow — buried stem produces more tubers.' },
  { id: 'corn', name: 'Sweet Corn', botanical: 'Zea mays', emoji: '🌽', cat: 'Vegetables',
    sun: 'full', spacing: 0.3, spread: 0.3, height: 2.2, water: 'high', days: '70–90 days',
    sow: 'Direct sow after soil warms', companions: ['bean', 'cucumber', 'zucchini'],
    avoid: ['tomato'],
    tip: 'Wind-pollinated — plant in blocks of at least 4×4, never a single row. Casts real shade; keep it on the north edge.' },
  { id: 'beet', name: 'Beet', botanical: 'Beta vulgaris', emoji: '🫜', cat: 'Vegetables',
    sun: 'part', spacing: 0.1, spread: 0.15, height: 0.3, water: 'medium', days: '55–70 days',
    sow: 'Direct sow 3 wks before last frost', companions: ['onion', 'kale', 'lettuce'],
    avoid: [],
    tip: 'Every "seed" is a cluster — thin seedlings ruthlessly and eat the thinnings.' },
  { id: 'radish', name: 'Radish', botanical: 'Raphanus sativus', emoji: '🌶', cat: 'Vegetables',
    sun: 'part', spacing: 0.05, spread: 0.08, height: 0.2, water: 'medium', days: '25–35 days',
    sow: 'Direct sow every 2 wks from early spring', companions: ['cucumber', 'lettuce', 'pea'],
    avoid: [],
    tip: 'Seed to salad in under a month — the impatient gardener’s best friend.' },

  // ---------- Herbs ----------
  { id: 'basil', name: 'Basil', botanical: 'Ocimum basilicum', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.25, spread: 0.3, height: 0.5, water: 'medium', days: '60 days',
    sow: 'Transplant well after last frost', companions: ['tomato', 'pepper'],
    avoid: ['sage'],
    tip: 'Pinch flower spikes the moment they appear or the leaves turn bitter.' },
  { id: 'rosemary', name: 'Rosemary', botanical: 'Salvia rosmarinus', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.6, spread: 0.7, height: 1.0, water: 'low', days: 'Perennial',
    sow: 'Transplant in spring', companions: ['carrot', 'sage', 'lavender'],
    avoid: [],
    tip: 'Hates wet feet — plant on a mound or slope in the driest bed you have.' },
  { id: 'thyme', name: 'Thyme', botanical: 'Thymus vulgaris', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.25, spread: 0.35, height: 0.25, water: 'low', days: 'Perennial',
    sow: 'Transplant in spring', companions: ['rosemary', 'strawberry', 'lavender'],
    avoid: [],
    tip: 'Thrives on neglect. A living mulch for bed edges and path cracks.' },
  { id: 'sage', name: 'Sage', botanical: 'Salvia officinalis', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.5, spread: 0.6, height: 0.6, water: 'low', days: 'Perennial',
    sow: 'Transplant in spring', companions: ['rosemary', 'broccoli', 'carrot'],
    avoid: ['cucumber', 'basil'],
    tip: 'Replace woody plants every 4–5 years; cuttings root easily in water.' },
  { id: 'mint', name: 'Mint', botanical: 'Mentha spicata', emoji: '🌱', cat: 'Herbs',
    sun: 'part', spacing: 0.45, spread: 0.6, height: 0.45, water: 'high', days: 'Perennial',
    sow: 'Transplant any time in season', companions: ['kale', 'broccoli'],
    avoid: [],
    tip: 'Will conquer the entire bed. Always contain it in a sunken pot.' },
  { id: 'cilantro', name: 'Cilantro', botanical: 'Coriandrum sativum', emoji: '🌿', cat: 'Herbs',
    sun: 'part', spacing: 0.15, spread: 0.2, height: 0.5, water: 'medium', days: '45–70 days',
    sow: 'Direct sow every 3 wks — it bolts fast', companions: ['spinach', 'bean'],
    avoid: ['fennel'],
    tip: 'Sow small amounts often; let one patch bolt for coriander seed.' },
  { id: 'dill', name: 'Dill', botanical: 'Anethum graveolens', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.25, spread: 0.3, height: 0.9, water: 'medium', days: '40–60 days',
    sow: 'Direct sow after last frost', companions: ['cucumber', 'lettuce', 'onion'],
    avoid: ['carrot', 'tomato'],
    tip: 'Swallowtail butterflies raise their caterpillars on it — plant extra to share.' },
  { id: 'chive', name: 'Chives', botanical: 'Allium schoenoprasum', emoji: '🌱', cat: 'Herbs',
    sun: 'part', spacing: 0.2, spread: 0.3, height: 0.35, water: 'medium', days: 'Perennial',
    sow: 'Transplant or divide in spring', companions: ['carrot', 'tomato', 'lettuce', 'rose'],
    avoid: ['bean', 'pea'],
    tip: 'The purple blossoms are edible and bees adore them. Shear to regrow.' },
  { id: 'parsley', name: 'Parsley', botanical: 'Petroselinum crispum', emoji: '🌿', cat: 'Herbs',
    sun: 'part', spacing: 0.2, spread: 0.3, height: 0.4, water: 'medium', days: '70–90 days',
    sow: 'Soak seed overnight; slow to germinate', companions: ['tomato', 'corn', 'rose'],
    avoid: ['lettuce'],
    tip: 'Biennial — overwinters, then flowers for beneficial insects in year two.' },
  { id: 'fennel', name: 'Fennel', botanical: 'Foeniculum vulgare', emoji: '🌿', cat: 'Herbs',
    sun: 'full', spacing: 0.3, spread: 0.4, height: 1.2, water: 'medium', days: '80–100 days',
    sow: 'Direct sow after last frost', companions: [],
    avoid: ['tomato', 'bean', 'cilantro', 'pepper'],
    tip: 'A famous bad neighbor — allelopathic to most crops. Give it a bed of its own.' },
  { id: 'lavender', name: 'Lavender', botanical: 'Lavandula angustifolia', emoji: '💜', cat: 'Herbs',
    sun: 'full', spacing: 0.6, spread: 0.8, height: 0.6, water: 'low', days: 'Perennial',
    sow: 'Transplant in spring', companions: ['rosemary', 'thyme', 'rose'],
    avoid: ['mint'],
    tip: 'Gravelly, lean soil and full sun — rich soil makes it floppy and short-lived.' },

  // ---------- Fruit ----------
  { id: 'strawberry', name: 'Strawberry', botanical: 'Fragaria × ananassa', emoji: '🍓', cat: 'Fruit',
    sun: 'full', spacing: 0.35, spread: 0.4, height: 0.2, water: 'medium', days: 'Perennial, fruits yr 1–2',
    sow: 'Crowns in early spring', companions: ['lettuce', 'bean', 'thyme', 'chive'],
    avoid: ['broccoli', 'kale', 'tomato'],
    tip: 'Renovate after harvest: mow leaves, thin runners, and they bear for years.' },
  { id: 'blueberry', name: 'Blueberry', botanical: 'Vaccinium corymbosum', emoji: '🫐', cat: 'Fruit',
    sun: 'full', spacing: 1.2, spread: 1.2, height: 1.5, water: 'high', days: 'Perennial shrub, fruits yr 2–3',
    sow: 'Plant bareroot in early spring', companions: ['thyme', 'rhubarb'],
    avoid: [],
    tip: 'Demands acidic soil (pH 4.5–5.5). Plant two varieties for cross-pollination.' },
  { id: 'raspberry', name: 'Raspberry', botanical: 'Rubus idaeus', emoji: '🍇', cat: 'Fruit',
    sun: 'full', spacing: 0.6, spread: 0.8, height: 1.5, water: 'medium', days: 'Perennial cane, fruits yr 2',
    sow: 'Bareroot canes in early spring', companions: ['garlic', 'chive'],
    avoid: ['potato', 'tomato'],
    tip: 'Runs underground — a buried root barrier keeps rows civilized.' },
  { id: 'rhubarb', name: 'Rhubarb', botanical: 'Rheum rhabarbarum', emoji: '🌺', cat: 'Fruit',
    sun: 'part', spacing: 0.9, spread: 1.2, height: 0.8, water: 'medium', days: 'Perennial, harvest yr 2+',
    sow: 'Crowns in early spring', companions: ['strawberry', 'garlic'],
    avoid: [],
    tip: 'Never harvest year one. Leaves are toxic — compost them; stalks are the prize.' },

  // ---------- Flowers ----------
  { id: 'marigold', name: 'Marigold', botanical: 'Tagetes patula', emoji: '🌼', cat: 'Flowers',
    sun: 'full', spacing: 0.2, spread: 0.25, height: 0.3, water: 'low', days: '50–60 days',
    sow: 'Direct sow after last frost', companions: ['tomato', 'potato', 'pepper'],
    avoid: [],
    tip: 'The classic pest-confuser — edge every vegetable bed with them.' },
  { id: 'nasturtium', name: 'Nasturtium', botanical: 'Tropaeolum majus', emoji: '🌺', cat: 'Flowers',
    sun: 'full', spacing: 0.25, spread: 0.4, height: 0.3, water: 'low', days: '55–65 days',
    sow: 'Direct sow after last frost', companions: ['zucchini', 'cucumber', 'bean'],
    avoid: [],
    tip: 'A trap crop for aphids, and every part is edible — peppery like arugula.' },
  { id: 'sunflower', name: 'Sunflower', botanical: 'Helianthus annuus', emoji: '🌻', cat: 'Flowers',
    sun: 'full', spacing: 0.45, spread: 0.5, height: 2.5, water: 'medium', days: '70–100 days',
    sow: 'Direct sow after last frost', companions: ['cucumber', 'corn'],
    avoid: ['potato', 'bean'],
    tip: 'A living trellis and bird feeder. Tall — keep on the north side or it will shade the bed.' },
  { id: 'zinnia', name: 'Zinnia', botanical: 'Zinnia elegans', emoji: '🌸', cat: 'Flowers',
    sun: 'full', spacing: 0.25, spread: 0.3, height: 0.8, water: 'low', days: '60–70 days',
    sow: 'Direct sow after last frost', companions: ['tomato', 'cucumber'],
    avoid: [],
    tip: 'Cut-and-come-again: the harder you harvest, the more it blooms.' },
  { id: 'chamomile', name: 'Chamomile', botanical: 'Matricaria chamomilla', emoji: '🌼', cat: 'Flowers',
    sun: 'part', spacing: 0.2, spread: 0.3, height: 0.5, water: 'low', days: '60–65 days',
    sow: 'Surface-sow in spring — needs light', companions: ['broccoli', 'onion', 'mint'],
    avoid: [],
    tip: 'Self-seeds gently. Harvest flowers at full open on a dry morning for tea.' },
  { id: 'rose', name: 'Rose', botanical: 'Rosa spp.', emoji: '🌹', cat: 'Flowers',
    sun: 'full', spacing: 0.9, spread: 1.0, height: 1.2, water: 'medium', days: 'Perennial shrub',
    sow: 'Bareroot in early spring', companions: ['garlic', 'chive', 'lavender', 'parsley'],
    avoid: [],
    tip: 'Garlic and chives underneath are the old-world defense against blackspot and aphids.' },
  { id: 'hosta', name: 'Hosta', botanical: 'Hosta spp.', emoji: '🍃', cat: 'Flowers',
    sun: 'shade', spacing: 0.6, spread: 0.9, height: 0.5, water: 'medium', days: 'Perennial',
    sow: 'Divisions in spring or fall', companions: ['fern'],
    avoid: [],
    tip: 'The deep-shade specialist — scorches in afternoon sun. Perfect under trees.' },
  { id: 'fern', name: 'Ostrich Fern', botanical: 'Matteuccia struthiopteris', emoji: '🌿', cat: 'Flowers',
    sun: 'shade', spacing: 0.6, spread: 0.9, height: 1.0, water: 'high', days: 'Perennial',
    sow: 'Crowns in spring', companions: ['hosta'],
    avoid: [],
    tip: 'Wants the dampest, darkest corner. Fiddleheads in spring are a delicacy.' },
  { id: 'spinach', name: 'Spinach', botanical: 'Spinacia oleracea', emoji: '🥬', cat: 'Vegetables',
    sun: 'part', spacing: 0.12, spread: 0.2, height: 0.25, water: 'medium', days: '40–50 days',
    sow: 'Direct sow 4–6 wks before last frost', companions: ['strawberry', 'pea', 'cilantro'],
    avoid: [],
    tip: 'A cool-weather sprinter — spring and fall only; summer heat sends it straight to seed.' },
];

const PLANT_INDEX = Object.fromEntries(PLANTS.map((p) => [p.id, p]));
const PLANT_CATS = [...new Set(PLANTS.map((p) => p.cat))];
