name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - "snake/**"
      # - "test/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./snake/package-lock.json"

      - name: Install Snake dependencies
        working-directory: ./snake
        run: |
          npm ci
          echo "Node modules installed. Contents of node_modules:"
          ls -la node_modules

      - name: Build Snake
        working-directory: ./snake
        run: |
          npm run build
          if [ ! -d "dist" ]; then
            echo "Error: dist directory was not created"
            exit 1
          fi
          echo "Build output:"
          ls -la dist/

      # Add similar steps for other projects when they're added
      # - name: Install Test dependencies
      #   working-directory: ./test
      #   run: npm ci

      # - name: Build Test
      #   working-directory: ./test
      #   run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare artifact
        run: |
          # First check if snake/dist exists and has content
          if [ ! -d "snake/dist" ] || [ -z "$(ls -A snake/dist)" ]; then
            echo "Error: snake/dist is empty or doesn't exist"
            exit 1
          fi

          # Create _site directory
          mkdir -p _site

          # Copy the entire snake/dist directory to _site
          cp -r snake/dist/. _site/

          # Verify _site has content
          echo "Contents of _site directory:"
          ls -la _site/

          if [ -z "$(ls -A _site)" ]; then
            echo "Error: _site directory is empty"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
