name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - "snake/**"
      # - "test/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./snake/package-lock.json"

      - name: Install Snake dependencies
        working-directory: ./snake
        run: npm ci

      - name: Build Snake
        working-directory: ./snake
        run: npm run build

      # Add similar steps for other projects when they're added
      # - name: Install Test dependencies
      #   working-directory: ./test
      #   run: npm ci

      # - name: Build Test
      #   working-directory: ./test
      #   run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment
        run: |
          echo "Checking snake build output..."
          ls -la ./snake/dist/

          echo "Creating deployment directory..."
          mkdir -p ./dist/snake

          echo "Copying files..."
          cp -r ./snake/dist/* ./dist/snake/ || echo "Copy failed"

          echo "Verifying deployment directory..."
          ls -la ./dist/
          ls -la ./dist/snake/

          # Add similar moves for other projects when they're added
          # mkdir -p ./dist/test
          # cp -r ./test/dist/* ./dist/test/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
