name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - "snake/**"
  workflow_dispatch:

# These are now top-level permissions that apply to all jobs
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write # Required for artifact upload/download

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./snake/package-lock.json"

      - name: Install dependencies
        working-directory: ./snake
        run: npm ci

      - name: Build
        working-directory: ./snake
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./snake/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
